name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-web
      run: cargo install cargo-web
    - name: Build
      run: cargo web build --verbose
    - name: Test
      run: cargo web test --verbose
